### PR TITLE
Updated Emojis and automation

### PR DESCRIPTION
**Pull request by stefanzweifel**
Hey there 👋

This PR adds a node build command to the project, to hopefully automate the creation of the snippets-file with new emojis in the future.

The bulk of the emojis and their shortcodes are build from the [gemoji](https://github.com/wooorm/gemoji) node package, which itself depends on the [gemoji](https://github.com/github/gemoji) ruby gem maintained by GitHub itself.

As there's still [a PR](https://github.com/github/gemoji/pull/136) open in the upstream github/gemoji repository to add emojis from the 2017 release, I've added a handful of emojis myself (See `otherSnippetsAndEmojis.js`).

Other stuff that has changed in comparison to `master`:

- I've deleted the `emoji-pack-unzipped` folder. Everytime a new build is created, there would be thousand of changes, as the UUID changes. Don't know if this okay or if this should be added back in 🤷‍♂️ 
- The `Emoji Pack.alfredsnippets` which can be downloaded and used in Alfred is committed to the repo

Let me know if something is unclear or something should be changed. Happy to help.

### CODE REVIEW

**Comment by califa** [comment]
Hey @stefanzweifel, thanks for the awesome changes! The build process is definitely going to help keep this up to date! I also think it's a good idea to remove the unzipped pack. I thought this would make diffing easier but it hadn't occurred to me that the UUID would change.

On closer inspection of the original pack, it looks like there are a few differences and I think we should keep it consistent for the existing user base. These changes were made to make the pack easier to use.
- It uses spaces rather than underscores between words.
- It includes additional tags for easier search, for instance `weather` on `:sunny_cloud:`. 
  - Note that Alfred changed how the search works at some point. These tags were placed in parentheses and that worked great with fuzzy search, but it's now broken and should be changed to `alias - tag tag`. 
  - This also goes for starting the snippet names (not keywords) with `:`, which also breaks search.
- It included a lot of manual optimizations. Some examples: 
  - `:bowing_man:` was changed to `:bow:`, `:upside_down_man:` changed to `:upside down:`, etc.
  - All flags were renamed to to `flag_XX` and included the country name as an alias for easier search.
  - etc etc, it was so long ago I can't even remember what else I put in there. I probably should have been thinking of how to keep this updated but ¯\\_(ツ)_/¯

Do you think it would be possible to:
1. Switch underscores out with spaces.
2. Extract the naming of these pre-existing emojis in the pack so that we don't override things people are used to.
3. Add aliases (already included in gemoji) as tags in the new emoji titles.
4. As a separate PR, I'll figure out how to remove the `:` from all of the emoji names (not keywords) so that search starts working again. Long overdue.

Thanks!

**Comment by stefanzweifel** [comment]
Thanks for the fast response.

While working on this PR I discovered that the emoji keywords differed from your original snippet pack. I thought I just give it a try, but totally forgot that it would break the workflow from existing users.

To your points:

1. Shouldn't be a problem, if you're okay when **all** underscores are replaced with spaces.
2. Shouldn't be too hard. I would try to extract all your *custom* keywords and little additions. When running the build process these custom rules would be re-applied.
3. No problem. Just to be sure and as an example, the title for 😆 would be:

```
😆 laughing satisfied - happy haha
```



*Based on this [data](https://github.com/github/gemoji/blob/master/db/emoji.json#L59-L73)*

4. I've removed the `:` from [this line of code](https://github.com/califa/alfred-emoji-pack/blob/38bd94c5b1e0a6d8b8fa6bc7921aaf9646cb969e/src/snippets.js#L19) and Alfred search seems to be working fine again




So 1., 3. and 4. are pretty easy. 2nd point will need some time…

**Comment by stefanzweifel** [comment]
I figured out a way to get the differences between your original Emoji Pack and the new version. I've generated [this file](https://github.com/stefanzweifel/alfred-emoji-pack-1/blob/af753eae9b338eb3f6a8535d533931f2bbcb132f/original-emoji-pack/original-vs-new-snippets.json) which contains a diff of the emojis.

Instead of picking, which old emoji keyword/name we should keep, I would suggest that we just keep all of them. I've added [a script](https://github.com/stefanzweifel/alfred-emoji-pack-1/blob/af753eae9b338eb3f6a8535d533931f2bbcb132f/src/build-snippets-archive/patchNewSnippets.js) which would patch these old emojis in.

[This file](https://github.com/stefanzweifel/alfred-emoji-pack-1/blob/af753eae9b338eb3f6a8535d533931f2bbcb132f/src/build-snippets-archive/index.js) is now responsible of building the archive.

You can download a patched build here:
[Emoji Pack - Patched.alfredsnippets.zip](https://github.com/califa/alfred-emoji-pack/files/2342252/Emoji.Pack.-.Patched.alfredsnippets.zip)


Let me know if you have further questions.

**Comment by califa** [comment]
@stefanzweifel this is amazing work. Is the best way to keep this up to date moving forward just rebuilding locally every time gemoji releases an update?

**Comment by stefanzweifel** [comment]
@califa Yeah I think so.

You could add a service like [dependabot](https://dependabot.com) to automatically retrieve PRs to be notified if a dependency updates and then create a new build.

**Comment by califa** [comment]
Great work! I'll update the download link and blog post shortly :)

**Comment by stefanzweifel** [comment]
Don't forget to rebuild the snippets file and push it to the repo. :shipit: ✌️

**Comment by califa** [comment]
Running the build will do that right?

**Comment by stefanzweifel** [comment]
Yes.

Just remove these lines: https://github.com/stefanzweifel/alfred-emoji-pack-1/blob/af753eae9b338eb3f6a8535d533931f2bbcb132f/src/build-snippets-archive/index.js#L7-L8

And uncomment these lines here:
https://github.com/stefanzweifel/alfred-emoji-pack-1/blob/af753eae9b338eb3f6a8535d533931f2bbcb132f/src/build-snippets-archive/index.js#L11-L12

**Comment by califa** [comment]
Just to be clear, the patch is what's adding the new emojis?

**Comment by stefanzweifel** [comment]
The patch is for adding the emojis which differ from `gemoji`. So stuff like `:bow:` and `:hands:`.

I'm updating my local fork and push a new PR, to make it a bit more clear ☺️

**Comment by stefanzweifel** [comment]
@califa Here's the PR with the updates file #2. (Ready to be merged, published, downloaded and used)

**Pull request merged**
